on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: seanmiddleditch/gha-setup-vsdevenv@v1
      - uses: microsoft/setup-msbuild@master
      - run: |
          for /f "delims=" %%d in ('dir /s /b "%VSINSTALLDIR%\vcvarsall.bat"') do @set myVCVARSALL=%%d
          if not defined myVCVARSALL exit 255
          call "%myVCVARSALL%"
          msbuild VGMPlay\\VGMPlay.sln /p:Platform=Win32;Configuration=Release;PlatformToolset=v142
        shell: cmd # forced to do so
      - uses: actions/upload-artifact@v2
        with:
          # Artifact name
          name: VGMPlay-CLI-win32-msvc
          # A file, directory or wildcard pattern that describes what to upload
          path: |
              Release/*.pdb
              Release/*.exe
              Release/*.dll
              Release/*.ini
              Release/*.txt
              !Release/vc142.pdb
