on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd VGMPlay
          make WINDOWS=1
#   runs-on: windows-latest
#   steps:
#     - uses: actions/checkout@v2
#     - uses: seanmiddleditch/gha-setup-vsdevenv@v1
#     - uses: microsoft/setup-msbuild@master
#     - run: |
#         for /f "delims=" %%d in ('dir /s /b "%VSINSTALLDIR%\vcvarsall.bat"') do @set myVCVARSALL=%%d
#         if not defined myVCVARSALL exit 255
#         call "%myVCVARSALL%" amd64 10.0.18362.0
#         msbuild VGMPlay\\VGMPlay.sln /p:Platform=x64;Configuration=Release;PlatformToolset=v142
#       shell: cmd # forced to do so
      - uses: actions/upload-artifact@v2
        with:
          # Artifact name
          name: VGMPlay-CLI-win32-mingw
          # A file, directory or wildcard pattern that describes what to upload
          path: |
              VGMPlay/*.exe
              VGMPlay/*.dll
              VGMPlay/*.ini
              VGMPlay/*.txt
              !VGMPlay/vgmspec171.txt
